http:

  routers:
    # Define a connection between requests and services
    to-whoami:
      rule: "Host(`whoami.localhost`) && PathPrefix(`/whoami/`) && PathPrefix(`/whoami`)"
      # If the rule matches, forward to the whoami service (declared below)
      service: whoami
      # Use the middleware declared below
      middlewares:
        - my-jwt-middleware

  services:
    # Define how to reach an existing service on our infrastructure
    whoami:
      loadBalancer:
        servers:
        - url: http://whoami:80

  middlewares:
    # Define a middleware that requires authentication
    my-jwt-middleware:
      plugin:
        my-jwt-middleware:
          secret: ThisIsMyVerySecret
          optional: false
          payloadHeaders:
            X-Custom-User-SUB: sub
            X-Custom-User-fullname: fullname
          authQueryParam: authToken
          authCookieName: authToken
          forwardAuth: true